#!/usr/bin/env bash
# $1 - snapshot name (e.g. r110-34)
# $2 - snapshot series (e.g. r110)
docker run --net=bridge -v /aptly-data:/data/aptly ajayhn/aptly aptly -distribution=$2 publish snapshot $1 $2
