#!/usr/bin/env bash
# $1 - parent repo name like ubuntu
timestamp=$(date +%s)
docker run --net=bridge -v /aptly-data:/data/aptly ajayhn/aptly aptly snapshot create $1-$timestamp from repo $1
docker run --net=bridge -v /aptly-data:/data/aptly ajayhn/aptly aptly publish snapshot $1-$timestamp $1
