#!/usr/bin/env bash
# $1 - snapshot series (e.g. opencontrail-r120-icehouse or opencontrail-stock-ubuntu1204-icehouse)
# $2 - endpoint (e.g. s3:opencontrail:)
docker run --net=bridge -v /aptly-data:/data/aptly ajayhn/aptly aptly publish drop $1 $2
